spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false
#
#cloud:
#  config:
#      enabled=false
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

